[package]
edition = "2024"
name = "tsum-macros"
version = "0.1.0"

[lib]
proc-macro = true

[dependencies]
const-random = "0.1"
convert_case = "0.6"
either = "1.13"
proc-macro2 = "1.0"
quote = "1.0"
syn = {version = "2.0", features = ["full", "visit", "extra-traits"]}
